### Create a new entity
POST http://localhost:8090/restapi/Students
Content-Type: application/json

{
  "firstName": "Daniel",
  "lastName": "Oyarzo",
  "courseSection": "DMIT2015-OE01-1253"
}

### GET All entity from REST API endpoint
GET http://localhost:8090/restapi/Students

### GET One entity from REST API endpoint
GET http://localhost:8090/restapi/Students/11

### UPDATE entity at the REST API endpoint - will replace all properties with the properties in the request body
PUT http://localhost:8090/restapi/Students/11
Content-Type: application/json

{
  "id": 11,
  "firstName": "Robin",
  "lastName": "Roche",
  "courseSection": "DMIT2015-OE01-1253",
  "version": 0
}

### DELETE entity at the REST API endpoint
DELETE http://localhost:8090/restapi/Students/11

